version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo "Pre-build phase"
      - chmod +x gradlew
  build:
    commands:
      - echo "Build phase"
      - ./gradlew build
  post_build:
    commands:
      - echo "Post-build phase"
      - ls -al build/libs # Adjust this command based on your build output directory

artifacts:
  type: codepipeline
  files:
    - build/libs/*.jar # Adjust this path based on your build output directory

  # Specify the artifacts to be passed to downstream stages of the CodePipeline
  name: MyOutputArtifacts
  namespace_type: 1